[package]
name = "luax"
version = "0.1.0"
authors = ["losfair <zhy20000919@hotmail.com>"]

[dependencies]
hexagon-vm-core = { path = "../hexagon-vm-core" }
serde = "1"
serde_derive = "1"
serde_json = "1"
