[package]
name = "luax"
version = "0.0.1"
authors = ["losfair <zhy20000919@hotmail.com>"]
description = "A Lua implementation"
license = "LGPL-3.0"
repository = "https://github.com/losfair/luax"

[dependencies]
hexagon = "0.1.2"
serde = "1"
serde_derive = "1"
serde_json = "1"
